require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EsolGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # EsolGroup. As you add validations to EsolGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EsolGroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all esol_groups as @esol_groups" do
      esol_group = EsolGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:esol_groups).should eq([esol_group])
    end
  end

  describe "GET show" do
    it "assigns the requested esol_group as @esol_group" do
      esol_group = EsolGroup.create! valid_attributes
      get :show, {:id => esol_group.to_param}, valid_session
      assigns(:esol_group).should eq(esol_group)
    end
  end

  describe "GET new" do
    it "assigns a new esol_group as @esol_group" do
      get :new, {}, valid_session
      assigns(:esol_group).should be_a_new(EsolGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested esol_group as @esol_group" do
      esol_group = EsolGroup.create! valid_attributes
      get :edit, {:id => esol_group.to_param}, valid_session
      assigns(:esol_group).should eq(esol_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EsolGroup" do
        expect {
          post :create, {:esol_group => valid_attributes}, valid_session
        }.to change(EsolGroup, :count).by(1)
      end

      it "assigns a newly created esol_group as @esol_group" do
        post :create, {:esol_group => valid_attributes}, valid_session
        assigns(:esol_group).should be_a(EsolGroup)
        assigns(:esol_group).should be_persisted
      end

      it "redirects to the created esol_group" do
        post :create, {:esol_group => valid_attributes}, valid_session
        response.should redirect_to(EsolGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved esol_group as @esol_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        EsolGroup.any_instance.stub(:save).and_return(false)
        post :create, {:esol_group => {}}, valid_session
        assigns(:esol_group).should be_a_new(EsolGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EsolGroup.any_instance.stub(:save).and_return(false)
        post :create, {:esol_group => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested esol_group" do
        esol_group = EsolGroup.create! valid_attributes
        # Assuming there are no other esol_groups in the database, this
        # specifies that the EsolGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EsolGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => esol_group.to_param, :esol_group => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested esol_group as @esol_group" do
        esol_group = EsolGroup.create! valid_attributes
        put :update, {:id => esol_group.to_param, :esol_group => valid_attributes}, valid_session
        assigns(:esol_group).should eq(esol_group)
      end

      it "redirects to the esol_group" do
        esol_group = EsolGroup.create! valid_attributes
        put :update, {:id => esol_group.to_param, :esol_group => valid_attributes}, valid_session
        response.should redirect_to(esol_group)
      end
    end

    describe "with invalid params" do
      it "assigns the esol_group as @esol_group" do
        esol_group = EsolGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EsolGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => esol_group.to_param, :esol_group => {}}, valid_session
        assigns(:esol_group).should eq(esol_group)
      end

      it "re-renders the 'edit' template" do
        esol_group = EsolGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EsolGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => esol_group.to_param, :esol_group => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested esol_group" do
      esol_group = EsolGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => esol_group.to_param}, valid_session
      }.to change(EsolGroup, :count).by(-1)
    end

    it "redirects to the esol_groups list" do
      esol_group = EsolGroup.create! valid_attributes
      delete :destroy, {:id => esol_group.to_param}, valid_session
      response.should redirect_to(esol_groups_url)
    end
  end

end
